# Generated by Django 5.1 on 2026-01-20 16:19

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffidavitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('tier', models.CharField(choices=[('low', 'Low Variability'), ('medium', 'Medium Variability'), ('high_precision', 'High Precision Required'), ('sensitive', 'Sensitive/High-Risk')], default='medium', max_length=20)),
                ('enabled_on_homepage', models.BooleanField(default=False, help_text='Show prominently on homepage')),
                ('default_mode', models.CharField(choices=[('instant', 'Instant Draft'), ('review_first', 'Review First'), ('intake_only', 'Intake Only')], default='review_first', max_length=20)),
                ('confidence_status', models.CharField(choices=[('learning', 'Learning'), ('controlled', 'Controlled'), ('confident', 'Confident')], default='learning', max_length=20)),
                ('policy_json', models.JSONField(default=dict, help_text='Type-specific rules for drafting + QA')),
                ('policy_version', models.PositiveIntegerField(default=1)),
                ('prompt_pack_version', models.PositiveIntegerField(default=1, help_text='Version of the prompt pack (system prompt + examples)')),
                ('template_version', models.PositiveIntegerField(default=1, help_text='Version of the PDF template')),
                ('intake_schema', models.JSONField(default=list, help_text='JSON schema defining required intake form fields')),
                ('scenario_library', models.JSONField(default=list, help_text='Known scenario patterns with tags')),
                ('is_instant_mode', models.BooleanField(default=False, help_text='If True, approved requests skip reviewer queue')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Affidavit Type',
                'verbose_name_plural': 'Affidavit Types',
                'db_table': 'affidavit_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('public', 'Public User'), ('commissioner', 'Commissioner'), ('reviewer', 'Reviewer'), ('admin', 'Admin')], db_index=True, default='public', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('commission_number', models.CharField(blank=True, max_length=50, null=True)),
                ('commission_expiry', models.DateField(blank=True, null=True)),
                ('payout_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount paid per completed affidavit', max_digits=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DecisionTreeNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='The simple, non-legal question to ask the user')),
                ('answer_value', models.CharField(blank=True, help_text='The answer choice from parent that leads here', max_length=200, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='affidavits.decisiontreenode')),
                ('result_affidavit_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_nodes', to='affidavits.affidavittype')),
            ],
            options={
                'verbose_name': 'Decision Tree Node',
                'verbose_name_plural': 'Decision Tree Nodes',
                'db_table': 'decision_tree_nodes',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_code', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('answers_json', models.JSONField(default=dict, help_text="User's answers to intake form questions")),
                ('draft_json', models.JSONField(default=dict, help_text='Structured draft with clause selections')),
                ('draft_text', models.TextField(blank=True, help_text='AI-generated draft of the affidavit')),
                ('final_text', models.TextField(blank=True, help_text='Final approved text (may be edited by reviewer)')),
                ('status', models.CharField(choices=[('draft', 'Draft (Intake in Progress)'), ('submitted', 'Submitted (Awaiting AI Draft)'), ('draft_ready', 'Draft Ready'), ('needs_clarification', 'Needs Clarification'), ('needs_review', 'Needs Human Review'), ('approved', 'Approved (Ready for Commissioner)'), ('completed', 'Completed (Stamped)'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=30)),
                ('clarification_question', models.TextField(blank=True, help_text='Specific question to ask user if needs_clarification')),
                ('qa_flags_json', models.JSONField(default=list, help_text='List of QA issues flagged by AI')),
                ('scenario_tags', models.JSONField(default=list, help_text='Detected scenario patterns for this request')),
                ('new_scenario_flag', models.BooleanField(default=False, help_text="True if this doesn't match known scenarios")),
                ('qa_overridden', models.BooleanField(default=False, help_text='Human changed the QA routing decision')),
                ('draft_edited_significantly', models.BooleanField(default=False, help_text='Reviewer changed wording beyond minor formatting')),
                ('override_notes', models.TextField(blank=True, help_text='Why the override was made')),
                ('policy_version_used', models.PositiveIntegerField(default=1)),
                ('prompt_version_used', models.PositiveIntegerField(default=1)),
                ('template_version_used', models.PositiveIntegerField(default=1)),
                ('user_edits_json', models.JSONField(default=list, help_text='Track which questions user changed/backtracked')),
                ('time_to_complete_seconds', models.PositiveIntegerField(blank=True, help_text='Total time from start to approval', null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_url', models.URLField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='affidavits/pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('affidavit_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='affidavits.affidavittype')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Request',
                'verbose_name_plural': 'Requests',
                'db_table': 'requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FrictionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Reason for refusal to sign')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('commissioner', models.ForeignKey(limit_choices_to={'role': 'commissioner'}, on_delete=django.db.models.deletion.CASCADE, related_name='friction_reports', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friction_reports', to='affidavits.request')),
            ],
            options={
                'verbose_name': 'Friction Report',
                'verbose_name_plural': 'Friction Reports',
                'db_table': 'friction_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(choices=[('draft', 'Draft Node'), ('qa', 'QA Node'), ('clarification', 'Clarification Node')], max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('timeout', 'Timeout')], default='success', max_length=20)),
                ('model_name', models.CharField(max_length=50)),
                ('prompt_version', models.PositiveIntegerField(default=1)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0, help_text='Response time in milliseconds')),
                ('input_json', models.JSONField(default=dict, help_text='Input sent to the AI')),
                ('output_json', models.JSONField(default=dict, help_text='Parsed output from AI')),
                ('raw_response', models.TextField(blank=True, help_text='Raw response text from AI')),
                ('error_message', models.TextField(blank=True)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_runs', to='affidavits.request')),
            ],
            options={
                'verbose_name': 'AI Run',
                'verbose_name_plural': 'AI Runs',
                'db_table': 'ai_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('submitted', 'Submitted'), ('draft_generated', 'Draft Generated'), ('qa_completed', 'QA Completed'), ('viewed', 'Viewed'), ('edited', 'Edited'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed (Stamped)'), ('locked', 'Locked'), ('unlocked', 'Unlocked'), ('pdf_generated', 'PDF Generated'), ('pdf_downloaded', 'PDF Downloaded'), ('commissioner_opened', 'Commissioner Opened'), ('commissioner_changed', 'Commissioner Changed')], db_index=True, max_length=30)),
                ('actor_role', models.CharField(blank=True, max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('details', models.JSONField(default=dict, help_text='Additional action-specific details')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_events', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='affidavits.request')),
            ],
            options={
                'verbose_name': 'Request Event',
                'verbose_name_plural': 'Request Events',
                'db_table': 'request_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewerEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField()),
                ('edited_text', models.TextField()),
                ('issue_type', models.CharField(choices=[('grammar', 'Grammar/Spelling'), ('legal_error', 'Legal Error'), ('missing_info', 'Missing Information'), ('contradiction', 'Contradiction'), ('formatting', 'Formatting Issue'), ('inappropriate', 'Inappropriate Content'), ('other', 'Other')], default='other', max_length=30)),
                ('issue_description', models.TextField(blank=True, help_text='Optional detailed description of the issue')),
                ('ai_flag_accepted', models.BooleanField(default=True, help_text="True if reviewer confirmed AI's flag was valid")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_edits', to='affidavits.request')),
                ('reviewer', models.ForeignKey(limit_choices_to={'role': 'reviewer'}, on_delete=django.db.models.deletion.CASCADE, related_name='edits_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reviewer Edit',
                'verbose_name_plural': 'Reviewer Edits',
                'db_table': 'reviewer_edits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payout_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stamped_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('commissioner', models.ForeignKey(limit_choices_to={'role': 'commissioner'}, on_delete=django.db.models.deletion.CASCADE, related_name='stamps', to=settings.AUTH_USER_MODEL)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stamp', to='affidavits.request')),
            ],
            options={
                'verbose_name': 'Stamp',
                'verbose_name_plural': 'Stamps',
                'db_table': 'stamps',
                'ordering': ['-stamped_at'],
            },
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['status', 'created_at'], name='requests_status_e58b13_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['request_code'], name='requests_request_d4c98b_idx'),
        ),
        migrations.AddIndex(
            model_name='requestevent',
            index=models.Index(fields=['request', 'action'], name='request_eve_request_ce4388_idx'),
        ),
        migrations.AddIndex(
            model_name='requestevent',
            index=models.Index(fields=['actor', 'created_at'], name='request_eve_actor_i_d066b5_idx'),
        ),
    ]
