# Generated by Django 5.1 on 2026-01-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affidavits', '0003_add_pdf_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Short bio for public display (commissioners)'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show this commissioner on the landing page'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Profile photo for public display', null=True, upload_to='profiles/'),
        ),
    ]
