# Generated by Django 5.1 on 2026-01-24 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affidavits', '0004_add_user_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='affidavittype',
            name='disallowed_phrases',
            field=models.JSONField(default=list, help_text='List of phrases AI should never use in drafts'),
        ),
        migrations.AddField(
            model_name='affidavittype',
            name='template_documents',
            field=models.JSONField(default=list, help_text='List of uploaded template documents [{filename, html_content, uploaded_at}]'),
        ),
        migrations.AddField(
            model_name='affidavittype',
            name='template_html',
            field=models.TextField(blank=True, default='', help_text='HTML template for AI drafting, extracted from uploaded examples'),
        ),
        migrations.CreateModel(
            name='AIBaseInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction_text', models.TextField(help_text='Global base instruction for AI drafting (used for all types)')),
                ('version', models.CharField(default='1.0', help_text='Version identifier for tracking changes', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Only one instruction can be active at a time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_instruction_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Base Instruction',
                'verbose_name_plural': 'AI Base Instructions',
                'db_table': 'ai_base_instructions',
                'ordering': ['-created_at'],
            },
        ),
    ]
