# Generated by Django 5.1 on 2026-01-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affidavits', '0005_add_ai_base_instruction_and_template_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisiontreenode',
            name='help_text',
            field=models.TextField(blank=True, help_text='Optional explanation shown to users below the question', null=True),
        ),
        migrations.AddField(
            model_name='decisiontreenode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
