# Generated by Django 5.1 on 2026-01-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affidavits', '0006_add_decision_tree_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisiontreenode',
            name='question_text',
            field=models.TextField(blank=True, default='', help_text='The simple, non-legal question to ask the user (required for question nodes, optional for result nodes)'),
        ),
    ]
