# Generated by Django 5.1 on 2026-01-24 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affidavits', '0007_make_question_text_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='commissioner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'commissioner'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
