# Generated by Django 5.1 on 2026-01-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affidavits', '0008_request_commissioner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airun',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='airun',
            name='raw_response',
            field=models.TextField(blank=True, default='', help_text='Raw response text from AI'),
        ),
    ]
