# Generated by Django 5.1 on 2026-01-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affidavits', '0009_fix_airun_error_message_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='clarification_question',
            field=models.TextField(blank=True, default='', help_text='Specific question to ask user if needs_clarification'),
        ),
    ]
