# Generated by Django 5.1 on 2026-01-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affidavits', '0010_fix_clarification_question_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.CharField(blank=True, help_text='Organization or law firm name for commissioner', max_length=200, null=True),
        ),
    ]
