# Generated by Django 5.1 on 2026-01-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affidavits', '0011_add_organization_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, help_text='Office/business address for commissioner', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='availability',
            field=models.JSONField(blank=True, default=dict, help_text='Commissioner availability schedule'),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_account_name',
            field=models.CharField(blank=True, help_text='Name on the bank account', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_account_number',
            field=models.CharField(blank=True, help_text='Bank account number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_branch',
            field=models.CharField(blank=True, help_text='Bank branch name or code', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Name of the bank for payments', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='payment_preference',
            field=models.CharField(blank=True, choices=[('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('cash', 'Cash')], default='bank_transfer', help_text='Preferred payment method', max_length=50, null=True),
        ),
    ]
