# Generated by Django 5.1 on 2026-01-29 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affidavits', '0012_add_commissioner_payment_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='stamp',
            name='paid',
            field=models.BooleanField(default=False, help_text='Whether this stamp has been paid out to commissioner'),
        ),
        migrations.AddField(
            model_name='stamp',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='When the payout was processed', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='payout_rate',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Amount paid per completed affidavit', max_digits=10),
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Total amount paid in this transaction', max_digits=10)),
                ('stamps_count', models.PositiveIntegerField(default=0, help_text='Number of stamps/affidavits included in this payment')),
                ('payment_reference', models.CharField(blank=True, help_text='Bank transfer reference or payment ID', max_length=100)),
                ('payment_method', models.CharField(blank=True, help_text='How payment was made (bank_transfer, cheque, cash)', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the payment')),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('commissioner', models.ForeignKey(limit_choices_to={'role': 'commissioner'}, on_delete=django.db.models.deletion.CASCADE, related_name='payment_logs', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(help_text='Admin who processed this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_processed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Log',
                'verbose_name_plural': 'Payment Logs',
                'db_table': 'payment_logs',
                'ordering': ['-paid_at'],
            },
        ),
    ]
