# Generated by Django 5.1 on 2026-01-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affidavits', '0013_stamp_paid_stamp_paid_at_alter_user_payout_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='commission_number',
            field=models.CharField(blank=True, help_text='Commission number must be unique', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number must be unique', max_length=20, null=True, unique=True),
        ),
    ]
