# Generated by Django 5.1 on 2026-01-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affidavits', '0014_alter_user_commission_number_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bank_account_number',
            field=models.CharField(blank=True, help_text='Bank account number must be unique', max_length=50, null=True, unique=True),
        ),
    ]
