# Generated by Django 5.1 on 2026-01-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affidavits', '0015_alter_user_bank_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Whether user has paid for this affidavit'),
        ),
        migrations.AddField(
            model_name='request',
            name='user_paid_at',
            field=models.DateTimeField(blank=True, help_text='When the user completed payment', null=True),
        ),
    ]
