# Generated by Django 5.1 on 2026-02-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affidavits', '0019_add_ticket_email_debounce'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_phone_verified',
            field=models.BooleanField(default=False, help_text='Whether the user has verified their phone number via OTP'),
        ),
    ]
