# Generated by Django 5.1 on 2026-02-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affidavits', '0020_user_is_phone_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestevent',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('submitted', 'Submitted'), ('draft_generated', 'Draft Generated'), ('qa_completed', 'QA Completed'), ('viewed', 'Viewed'), ('edited', 'Edited'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed (Stamped)'), ('locked', 'Locked'), ('unlocked', 'Unlocked'), ('pdf_generated', 'PDF Generated'), ('pdf_downloaded', 'PDF Downloaded'), ('commissioner_opened', 'Commissioner Opened'), ('commissioner_changed', 'Commissioner Changed'), ('ticket_created', 'Ticket Created'), ('ticket_updated', 'Ticket Updated'), ('payment_confirmed', 'Payment Confirmed')], db_index=True, max_length=30),
        ),
    ]
