# Generated by Django 5.1 on 2026-02-06 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affidavits', '0021_add_payment_confirmed_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionerSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(db_index=True)),
                ('is_booked', models.BooleanField(default=False)),
                ('commissioner', models.ForeignKey(limit_choices_to={'role': 'commissioner'}, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to=settings.AUTH_USER_MODEL)),
                ('request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_slot', to='affidavits.request')),
            ],
            options={
                'verbose_name': 'Commissioner Slot',
                'verbose_name_plural': 'Commissioner Slots',
                'db_table': 'commissioner_slots',
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['commissioner', 'start_time'], name='commissione_commiss_d37b16_idx'), models.Index(fields=['start_time'], name='commissione_start_t_83432c_idx')],
                'unique_together': {('commissioner', 'start_time')},
            },
        ),
    ]
