# Generated by Django 5.1 on 2026-02-08 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affidavits', '0022_commissionerslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('grammar', 'Grammar/Spelling'), ('legal_error', 'Legal Error'), ('missing_info', 'Missing Information'), ('contradiction', 'Contradiction'), ('formatting', 'Formatting Issue'), ('inappropriate', 'Inappropriate Content'), ('other', 'Other')], default='other', max_length=30)),
                ('message', models.TextField(help_text='Minimal, actionable feedback (keep short and specific)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_feedback', to='affidavits.request')),
                ('reviewer', models.ForeignKey(limit_choices_to={'role': 'reviewer'}, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reviewer Feedback',
                'verbose_name_plural': 'Reviewer Feedback',
                'db_table': 'reviewer_feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
