# Generated by Django 5.1 on 2026-02-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affidavits', '0024_submitfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='affidavittype',
            name='validation_rules',
            field=models.JSONField(default=list, help_text='Custom validation rules for this affidavit type (field comparisons, required_if, etc.)'),
        ),
    ]
