# Generated by Django 5.1 on 2026-02-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affidavits', '0025_add_validation_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_code',
            field=models.CharField(blank=True, help_text='Current OTP code for verification', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, help_text='Time when the current OTP was generated', null=True),
        ),
    ]
