# Generated by Django 5.1 on 2026-02-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affidavits', '0026_user_otp_code_user_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionerslot',
            name='appointment_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled_by_commissioner', 'Cancelled by Commissioner'), ('cancelled_by_user', 'Cancelled by User')], default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='commissionerslot',
            name='decision_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commissionerslot',
            name='decision_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
