# Generated by Django 5.1 on 2026-02-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affidavits', '0027_add_appointment_status_to_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number', max_length=20, null=True),
        ),
    ]
