# Generated by Django 5.1 on 2026-02-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affidavits', '0028_allow_duplicate_phone_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number', max_length=50, null=True),
        ),
    ]
