# Generated by Django 5.1 on 2026-02-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affidavits', '0029_widen_phone_number_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='affidavittype',
            name='placeholder_mapping',
            field=models.JSONField(default=dict, help_text='Maps template {{placeholders}} to intake_schema question IDs. Example: {"full_name": "full_name", "address": "residential_address"}'),
        ),
    ]
