# Generated by Django 5.1 on 2026-02-22 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affidavits', '0030_add_placeholder_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewerfeedback',
            name='affidavit_type',
            field=models.ForeignKey(blank=True, help_text='Auto-populated from request for filtering feedback by type', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_feedback', to='affidavits.affidavittype'),
        ),
        migrations.AddField(
            model_name='reviewerfeedback',
            name='feedback_target',
            field=models.CharField(choices=[('drafter', 'AI Drafter'), ('policy', 'Policy/Template Generator'), ('both', 'Both')], default='drafter', help_text='Which AI system this feedback should improve', max_length=20),
        ),
        migrations.AddField(
            model_name='reviewerfeedback',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive feedback is excluded from AI prompts'),
        ),
        migrations.AddField(
            model_name='reviewerfeedback',
            name='times_seen',
            field=models.PositiveIntegerField(default=0, help_text='How many times this feedback has been injected into prompts'),
        ),
    ]
