# Generated by Django 5.1 on 2026-02-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affidavits', '0031_add_feedback_learning_loop'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewerfeedback',
            name='original_snippet',
            field=models.TextField(blank=True, default='', help_text='The original AI-generated text that was changed'),
        ),
        migrations.AddField(
            model_name='reviewerfeedback',
            name='revised_snippet',
            field=models.TextField(blank=True, default='', help_text='The reviewer-corrected replacement text'),
        ),
        migrations.AlterField(
            model_name='reviewerfeedback',
            name='message',
            field=models.TextField(blank=True, default='', help_text='Manually written feedback note (optional when original/revised snippets are provided)'),
        ),
    ]
