# Generated by Django 5.1 on 2026-02-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affidavits', '0032_add_feedback_snippets'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewerfeedback',
            name='summary',
            field=models.CharField(blank=True, help_text='AI-generated one-liner lesson distilled from the correction (e.g. use present perfect tense)', max_length=300, null=True),
        ),
    ]
